### ISSUE TITLE
Alpine error

### ISSUE THREAD

**Issue by djolereject** [ruby-ml/xgboost-ruby#8]
I have an issue when I run the app on Alpine Docker container that doesn't happen on the Mac that I use for development. Stack trace somehow lists all of the gems and then hundreds of lines of trace, but starting with this:

```
web_1        | /usr/local/bundle/gems/xgb-0.7.1/lib/xgboost/dmatrix.rb:125: [BUG] Segmentation fault at 0x00000000000f6ee6
web_1        | ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux-musl]
web_1        | 
web_1        | -- Control frame information -----------------------------------------------
web_1        | c:0098 p:---- s:0708 e:000707 CFUNC  :XGDMatrixSetFloatInfo
web_1        | c:0097 p:0051 s:0700 e:000698 METHOD /usr/local/bundle/gems/xgb-0.7.1/lib/xgboost/dmatrix.rb:125
web_1        | c:0096 p:0007 s:0692 e:000691 METHOD /usr/local/bundle/gems/xgb-0.7.1/lib/xgboost/dmatrix.rb:74
web_1        | c:0095 p:0295 s:0687 e:000686 METHOD /usr/local/bundle/gems/xgb-0.7.1/lib/xgboost/dmatrix.rb:56 [FINISH]
web_1        | c:0094 p:---- s:0674 e:000673 CFUNC  :new
```

If there is need to elaborate further, I attached the whole [dump file](https://github.com/ruby-ml/xgboost-ruby/files/11463027/dump.txt).

Thanks.

**Comment by ankane** [comment]
Hi @djolereject, there's not a shared library for musl yet, but will try to create one.

**Comment by djolereject** [comment]
Hi @ankane, thanks for responding, but please could you be a bit more specific? What can I do to avoid musl then or is there any other way to use your library because I'm flexible about the environment and I fairly like this lib.

**Comment by ankane** [comment]
Just pushed 0.7.2, which will work on Alpine.

**Comment by djolereject** [comment]
Hi @ankane, thanks for such a speedy response!
